version: '3.8'

services:
  api:
    build: ./BlogAPI
    ports:
      - "5119:5119"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AppDbConnectionString=Server=db;Database=database_blog;User=root;Password=Teste123
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: database_blog
      MYSQL_ROOT_PASSWORD: Teste123
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
