version: '3.8'

services:
  api:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    working_dir: /src
    volumes:
      - ./BlogAPI:/src
    ports:
      - "5119:5119"
    command: dotnet run --urls http://0.0.0.0:5119
#     depends_on:
#       - db

#   db:
#     image: mysql:8.0
#     restart: always
#     environment:
#       MYSQL_DATABASE: database_blog
#       MYSQL_ROOT_PASSWORD: Teste123
#     ports:
#       - "3306:3306"
#     volumes:
#       - db_data:/var/lib/mysql
#       - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

# volumes:
#   db_data:
